---
# tasks file for config-inactivity-timeout-on-ocp4
- name: Authenticate with the API
  command: >
    {{ openshift_cli }} login \
      -u {{ ocp_cluster_user }} \
      -p {{ ocp_cluster_user_password }} \
      --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port | d('6443', true) }}
  register: login_out

- name: '{{ ansible_name_module }} | import_tasks | Use oc apply -f  to patch oauth resources'
  include_tasks: apply-template.yml
  when:
    - apply_template is defined
    - apply_template | bool

- name: '{{ ansible_name_module }} | import_tasks | Use oc patch to patch oauth resources'
  include_tasks: patch.yml
  when:
    - not apply_template is defined or not apply_template | bool
